name: API Deployment

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - 'model/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        cd api
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        # Здесь команды для деплоя на ваш хостинг (Render, Heroku и т.д.)
        echo "Деплой API должен быть настроен здесь"
        # Пример для Render:
        # curl -s -X POST \
        #   -H "Authorization: Bearer $RENDER_API_KEY" \
        #   -H "Content-Type: application/json" \
        #   -d '{"serviceId": "your-service-id"}' \
        #   https://api.render.com/v1/services/your-service-id/deploys